### ISSUE TITLE
python in relocate_once.py

### ISSUE THREAD

**Issue by dimpase** [sagemath/binary-pkg#15]
I wonder whether it's safer to use `/usr/bin/python` rather than `/usr/bin/env python`.
In particular on OSX people tend to set their default python to all sorts of things, see e.g.
[sage-suppport](https://groups.google.com/d/msg/sage-support/9hg7fui1rjc/IYU_pIx0BAAJ), and this with some probability nukes the installation. I believe that `/usr/bin/python` should be very safe on any sane Linux, too.

**Comment by vbraun** [comment]
But there is no guarantee that python is in /usr/bin. If the python thats in your PATH is broken then things *should* fail.

**Comment by dimpase** [comment]
On any OSX and Linux system we distribute Sage binary packages for, it is the case that there is, by right, a Python in /usr/bin - and a fairly new one, too.
(Anyone who has an interestingly hacked system without such a Python is much more likely to do a source install of Sage anyway :-))

And I suppose it's not about a totally broken Python, it's about a Python that has stuff which breaks the binary install, e.g. Anaconda does this, homebrew does it...

**Comment by vbraun** [comment]
The original sage-support seems to be about python 3 compatibility, this is now fixed. The relocate_once.py script should just work with any reasonable Python version.
