### ISSUE TITLE
disk space requirements

### ISSUE THREAD

**Issue by saliola** [sagemath/binary-pkg#22]
I am trying to create a binary for CentOS 7. Here is what I have done so far:

- I created a VM with a minimal CentOS 7 installation with a 25GB hard drive.
- I installed the dependencies per the instructions in the SageMath installation guide.
- I cloned sagemath/binary-pkg.
- I changed the branch in sage.yaml from develop to master.
- I executed: make bdist-sage-linux

Eventually, it failed with a "No space left on device" error. Is it expected that this process would take more than 20GB of disk space? If so, then how much disk space do I need? It would be really nice if the instructions were updated with information about the disk space requirements.

[This question also appeared as part of an email to sage-devel: https://groups.google.com/d/msg/sage-devel/nftiNNR_5cE/bT0di2g1CQAJ]

**Comment by saliola** [comment]
See also https://github.com/sagemath/binary-pkg/issues/20 (staging should delete after being done)

**Comment by vbraun** [comment]
Not sure how much you need, I'm guessing between 20 and 30GB for all intermediate build artifacts....   And everything (except the generated binary tarball) can be deleted when done.
