### ISSUE TITLE
Run configure before make

### ISSUE THREAD

**Issue by slel** [sagemath/binary-pkg#23]
Required for Sage >= 9.2.beta2 due to

- [Sage Trac ticket 29316: Require ./configure before make](https://trac.sagemath.org/ticket/29316)

**Comment by vbraun** [comment]
Thanks, fixed now!

**Comment by slel** [comment]
I see this is fixed by commit 6b071f392072b2226935bf8c985c6bdcd695ab41 -- thanks!
