### ISSUE TITLE
Support older processors by avoiding avx, avx2, bmi2 instructions

### ISSUE THREAD

**Issue by slel** [sagemath/binary-pkg#31]
Setting `CFLAGS` to `-mno-avx -mno-avx2 -mno-bmi2`
should help the produced binaries work on older processors.

That was done successfully for the macOS app, see

- https://github.com/3-manifolds/Sage_macOS/blob/v1.2/Sage_framework/build_sage.sh#L3

Similar problems were reported with the Sage 9.2 Linux binaries, see e.g.

- https://groups.google.com/g/sage-support/c/KZFZBoI6xJk

**Comment by vbraun** [comment]
This should be done on the Sage side, building with SAGE_FAT_BINARY should set the appropriate CFLAGS for the package that uses the wrong settings. I don't have a way to test, though.

I've transferred the ticket to https://trac.sagemath.org/ticket/32434
