### ISSUE TITLE
recompilation after relocation

### ISSUE THREAD

**Issue by dkrenn** [sagemath/binary-pkg#4]
Suppose we have a successful installation (relocation) of the built binary package (thus it works). When starting a (re-)building of the software in the new directory there should not be any need to recompile etc. anything, i.e. no targets/files should be outdated. However, this is not the case. For example, noticed with SageMath: all cythonized files have to be recompiled and the full documentation has to be rebuilt. This is probably due to some timestamp-issues.

**Comment by vbraun** [comment]
This seems because we exclude build artifacts, specifically the doctrees (600MB) and some cython output (>1GB). Removing  the

```
      - exclude: local/share/doc/sage/doctrees/**   # weird string terminators
      - exclude: src/build/lib.*/**
      - exclude: src/build/temp.*/**
```

will probably save a few minutes compiling but make the tarball significantly larger
