### ISSUE TITLE
how does one make a dist of an existing sage installation?

### ISSUE THREAD

**Issue by dimpase** [sagemath/binary-pkg#5]
Is this supported?
It's certainly does not seem to be documented; quick browsing through Makefile and sage.yaml seems to suggest that it is only ever meant to do the full cycle of pulling from a repo, building, etc etc.

**Comment by vbraun** [comment]
The intended use to go through the full cycle.
- Sets SAGE_FAT_BINARY=yes
- Builds in a long, nonpredictable path that can be reliably truncated for binary installs
