### ISSUE TITLE
Wrong directory error while attempting to follow the instruction

### ISSUE THREAD

**Issue by dimpase** [sagemath/binary-pkg#6]
```
 $ make package-sage
 make -j4 checkout-sage
 make[1]: Entering directory `/home/dima/software/sage/binary-pkg'
 ./tools/toolaid/bootstrap
Wrong directory? (/home/dima/software/sage/binary-pkg)
make[1]: *** [/home/dima/software/sage/binary-pkg/tools/binary-pkg/activate] Error 1
make[1]: Leaving directory `/home/dima/software/sage/binary-pkg'
make: *** [package-sage] Error 2
```

it is totally unclear from docs or sources how the thing is supposed to know which Sage root it should take to build the distribution.

**Comment by vbraun** [comment]
You don't have the git repository, this program is meant to be run directly from the repo.

**Comment by dimpase** [comment]
Do you mean `make`, or some other program? The 1st line of Makefile says

```
     export REPO_ROOT:=$(shell git rev-parse --show-toplevel)
```

needless to say, if you follow your TL;DR in Readme, that's the error you get, full stop.

**Comment by vbraun** [comment]
The readme starts with "git clone https://github.com/sagemath/binary-pkg.git"; If you do that then you have the git repo and everything will work fine. Which steps did you do that did not work for you?

**Comment by vbraun** [comment]
You can clone it wherever you want. By design you you must compile Sage in a special directory whose name is decided by binary-pkg so it makes no sense to have it located inside the Sage repo.

**Comment by dimpase** [comment]
It is ludicrous, and a clear regression, that you cannot make a binary
release of your custom Sage tree.
It didn't cross my mind that it could be the case.

**Comment by vbraun** [comment]
Nobody else creates binaries from random builds, and for a good reason.

Besides, what we did for years didn't and couldn't work consistently. It worked after fudging around with library versions for the most popular distros but never had a chance of being a 100% reliable solution. Not to even mention the security issues.

**Comment by dimpase** [comment]
I am not saying we need to resurrect the old unreliable setup with LD_LIBRARY_PATH, but "noone else creates binaries from random builds" sounds very hard to believe.
Besides, what does prevent binary-pkg from being adapted to making binaries from a random build, besides few minor tweaks?

**Comment by vbraun** [comment]
Fundamentally, its easy to truncate a null-terminated string but you can't grow it without deep understanding of the binary format. Hence if you bake in paths that are too short then you can't change them.

**Comment by dimpase** [comment]
It explains why one needs to rebuild everything, but it does not explain
why there is no option to rebuild an existing source tree, in a custom
location with long enough paths...
